CREATE TABLE FT(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[NomeFile] [nvarchar](150) NULL,
 CONSTRAINT [PK_FattureRicevute] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

INSERT INTO FattureRicevute (NomeFile) VALUES ('1.zip');

 
