name: CI

on:
  push:
    branches: [ master ]



jobs:  
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: find dacpac
      run: |
        echo "ls TestCDCI\DB"
        ls "TestCDCI\DB"
        ls "c:\Program Files\Microsoft SQL Server\130\LocalDB\Binn"
    - name: Create DB Instance 
      run: 
        SqlLocalDB start MSSQLLocalDB 
    - name: Create DB SDI
      run: 
        sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "create database sdi;"
    - name: update database schema using dacpac
      run: >
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\sqlpackage" /a:Publish /sf:'TestCDCI\DB\sdi.dacpac' /tcs:"${{ secrets.DATABASE_CONNECTION_STRING }}" /p:BlockOnPossibleDataLoss=False


    

   
