name: CI

on:
  push:
    branches: [ master ]



jobs:  
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: find dacpac
      run: |
        echo "ls TestCDCI\DB"
        ls "TestCDCI\DB"
    - name: Create DB Instance 
      run: |
        # MSSQLLocalDB is the default SQL LocalDB instance
        SqlLocalDB start MSSQLLocalDB
        SqlLocalDB info MSSQLLocalDB
        sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "create database sdi;"
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    - name: Setup Nuget.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore packages
      run: nuget restore TestCDCI.sln
    - name: Build the solution
      run: msbuild TestCDCI.sln -p:Configuration=Debug


    

   
