name: CI

on:
  push:
    branches: [ master ]



jobs:  
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: find dacpac
      run: |
        echo "ls TestCDCI\DB"
        ls "TestCDCI\DB"
        Import-Module -Name SQLPS -DisableNameChecking
        'SQL01', 'SQL02' | ForEach-Object {Get-ChildItem -Path &quot;SQLSERVER:\SQL\$_&quot;} | Select-Object -Property ComputerNamePhysicalNetBIOS, Name, DisplayName, InstanceName
    - name: update database schema using dacpac
      uses: abelsquidhead/dacpac-deploy@master
      with:
        connectionString: ${{ secrets.DATABASE_CONNECTION_STRING }}
        dacpac: 'TestCDCI\DB\sdi.dacpac'
        additionalArguments: '/p:BlockOnPossibleDataLoss=False'

    

   
