name: CI

on:
  push:
    branches: [ master ]



jobs:  
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    - name: Setup Nuget.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Restore packages
      run: nuget restore TestCDCI.sln
    - name: Build the solution
      run: msbuild TestCDCI.sln -p:Configuration=Debug
    

  test:
    runs-on: windows-latest
    
    steps:
    - name: Running test
      run:  '& "$(vswhere -property installationPath)\Common7\IDE\Extensions\TestPlatform\VSTest.Console.exe" Tests\bin\Debug\Tests.dll'
